theme = "dark_plus"

[editor]
default-line-ending = "lf"
line-number = "absolute"
color-modes = true
cursorline = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"
shell = ["bash", "-ic"]

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "version-control",
  "spinner",
]
center = [
  "position",
  "position-percentage",
  "file-name",
  "file-modification-indicator",
]
right = [
  "workspace-diagnostics",
  "selections",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "â”‚"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = false
git-ignore = true

[keys.normal]
X = "extend_line_up"

# bindings
[keys.normal."space"]
f = "file_picker"
F = "file_picker_in_current_buffer_directory"
